### ISSUE TITLE
Create Donate page

### ISSUE THREAD

**Issue by bcantello** [spacelabdev/spacelab-react#163]
The goal is for this to include the ability to donate to spacelab via paypal, and then potentially through other methods in the future. 

https://www.paypal.com/us/webapps/mpp/non-profits/fundraising/donate-button?CampaignName=VanityURL-DonateButton

**Comment by MattPat1981** [comment]
Copy for the donations page is as follows 
note: edits are OK, run them by Brandon or Matt or Sven  or Ollie (or Phaly until she moves on to Microsoft). If you are one of these four people run it by another before going to print:

copy:

Title = Your Contribution Matters
Paragraph 1 body = The SpaceLab would not exist without your support and contributions. We ask that you give only what you can, and that you consider making it a monthly donation to help the cause along. We appreciate you.

<ul>Paragraph 2 body = Your support will help us:
<li>Pay interns, fellows and mentors</li>
<li>Provide grants and scholarships</li>
<li>Power the space applications that you enjoy</li>
</ul>
