### ISSUE TITLE
Fix About Page Slider Layout

### ISSUE THREAD

**Issue by aanand93** [spacelabdev/spacelab-react#212]
The decision was made to push the current "About" page set-up, and to not group everyone into a "currently active" and "past" groupings until a future release. We already had a "prior cohort" though, so:

- Currently we have "Prior Cohorts" showing only the December Cohort and 3 "Additional Contributors" who are front-end or full-stack engineers.

- Currently we also have a lot of folks in the "Current Team" section that are not currently participating at all

- This setup is misleading, and I'd rather have everyone shown to display our community as it will take time to fix the nuance, thus...

**ACTION 1**: Please move all the participants from "Prior Cohorts" and "Additional Contributors" to the "Frontend Developers" section
**ACTION 2**: Please remove the buttons for "Current Team" and "Past Cohorts" leaving only the sub-groupings visible

**Comment by DrDrewCain** [comment]
(First action has been put into in-progress) not sure about what you mean by "removing" the buttons for current team and past cohort, wouldn't that break the slider?

**Comment by DrDrewCain** [comment]
* Currently we also have a lot of folks in the "Current Team" section that are not currently participating at all

Do we have a list? Do we know who on current team is participating? Are we currently putting everyone we've had past/current into "current team" until final release?

**Comment by DrDrewCain** [comment]
Is this suggesting that we remove the onclick for Current and Past action button?

**Comment by aanand93** [comment]
Matt can make that call whether we are keeping all the inactive users or how we structure them. As of right now I believe we are keeping all of them.  I think that we should put the active members at the top of each section and still keep everyone.

**Comment by aanand93** [comment]
We would remove the buttons entirely
