### ISSUE TITLE
delete termly cookie banner

### ISSUE THREAD

**Issue by lauren-owen-spacelab** [spacelabdev/spacelab-react#235]
please delete the following on the live website:
<script
  type="text/javascript"
  src="https://app.termly.io/embed.min.js"
  data-auto-block="on"
  data-website-uuid="c7ad4eff-e2e8-4709-8ed8-70a9ccf5b66c"
  ></script>
because I am going to deploy a cookie banner using GTM instead.

**Comment by MattPat1981** [comment]
opening ticket

**Comment by MattPat1981** [comment]
deleted the code on the live server. This still needs to be done on the website. 

Please delete this code from /public/index.html

**Comment by MattPat1981** [comment]
Update--the code revision still needs to be made and committed to this repo, then merged with main and RELEASE before we can close this ticket.

**Comment by DrDrewCain** [comment]
@MattPat1981 completed.
