### ISSUE TITLE
Update About Page: Update Project Leads

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#239]
Update all the project leads so they are accurate and make them the first card to appear in each section on the About page.

**Comment by UjjawalTyagi123** [comment]
I can work on this issue if you make me clear about what actually you want.

**Comment by DrDrewCain** [comment]
> I can work on this issue if you make me clear about what actually you want.

It's all good, this is for spacelab cohort to add people participating in the internship! 👍🏻
