### ISSUE TITLE
Bug Fix: Update Browser Icon

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#241]
Right now the browser icon for the site is the default React symbol.  Update this to be the Spacelab logo.

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this?

**Comment by AryanBakliwal** [comment]
Hi! I want to work on this issue, please assign me to this. It would help me a lot as a beginner.

**Comment by UjjawalTyagi123** [comment]
I'm done same thing in my project it is very easy for me, could you please give me a chance..
