### ISSUE TITLE
Bug Fix: Homepage our vision container

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#282]
The Our Vision section overflows the container on small screens, should be an easy fix!
![image](https://user-images.githubusercontent.com/92811107/232136543-c10acc1a-e2de-4293-a714-1565874d0e1b.png)

**Comment by k-deepak04** [comment]
i would like to contribute

**Comment by k-deepak04** [comment]
#291 fixed your issue
![Screenshot 2023-04-15 030245](https://user-images.githubusercontent.com/96341431/232160037-188ed11d-d16b-4e46-b342-8b3be46d2da2.png)
![Screenshot 2023-04-15 030256](https://user-images.githubusercontent.com/96341431/232160042-a42221f3-9138-408a-bce1-274767ba7719.png)
