### ISSUE TITLE
Improvement: Reusable Search Bar Component

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#328]
Improvements to be made:
- Style scroll bar in results container
- Remove blue x that appears on right side of container on focus
- Move search icon farther to the left of the container (so it fits nicely)
- Add functionality so that when the user clicks on a search term, that term becomes the placeholder for the search bar
- When the user clicks outside of the search bar, the icon should switch from x to search

If you notice any other bugs/improvements feel free to comment below and add to my list!

**Comment by manuel12** [comment]
Hello. I would like to work on this issue if that's ok :)

**Comment by lauraehiller** [comment]
@manuel12 That would be great!  Request me as a reviewer when you're ready with a PR:)

**Comment by manuel12** [comment]
@lauraehiller Is there anything more needed here? :)

**Comment by ryanfchase** [comment]
Scroll bar container needs to be styled:

![image](https://github.com/user-attachments/assets/f1badca2-7082-4d5b-9723-8566fd63ece1)

**Comment by ryanfchase** [comment]
Blue x:

![image](https://github.com/user-attachments/assets/3338d38c-f97f-4a5c-895b-4979803d1991)

**Comment by fjstria** [comment]
Addressed by #364.
