### ISSUE TITLE
Improvement: Transition Components to Mobile First Styles

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#347]
All site styles should be transitioned to mobile-first design with breakpoints at:
- 576px for portrait phones
- 768px for tablets
- 992px for laptops
- 1200px for large devices

Media queries should use the screen and min-width properties like so:
	@media screen and (min-width: 1024px) {
		...
	}
Note: using min-width is considered the best practice for mobile-first design.  It is also compatible with older browsers that do not recognize media queries.

Non-extensive list of components that need to be transitioned:
-components/blogArchives/blogArchives.scss
-components/blogArchivesCard/blogArchivesCard.scss
-components/dynamicSearchBar/SearchBar.scss
-components/footer/footer.scss
-components/heroImage/heroImage.scss

**Comment by manuel12** [comment]
@lauraehiller Hello I would like to work on this :) Could I get it assigned?

**Comment by fjstria** [comment]
Website is functional on mobile. Let's address each component individually duriing future redesigns.
