### ISSUE TITLE
Bug Fix: SignUp landing page styles are global styles

### ISSUE THREAD

**Issue by megbuch** [spacelabdev/spacelab-react#352]
Sign Up landing page styles, specifically ".overlay", are overriding Participate landing page styles.

## The Problem
``` 
// signUp.scss contains global styles

.overlay { 
    background: rgba(0, 0, 0, 0.85);
    height: 100%;
    width: 100vw;
    position: fixed;
    z-index: 100;
}
```

## The Effects of the Problem on Participate Landing Page

Each of the image elements that are overlayed use the className of `overlay`, so this happens.

![Screenshot 2023-05-19 125028](https://github.com/spacelabdev/spacelab-react/assets/115611931/b823f6db-d38c-460b-bb37-4605046344f0)

How it should be:

https://github.com/spacelabdev/spacelab-react/assets/115611931/9ffa8a8a-d191-4db7-8b59-17c28739d702

## Proposed Solution, or Something Similar
``` 
// signUp.scss

.sign-up {     // add this line
    .overlay {   
          background: rgba(0, 0, 0, 0.85);
          height: 100%;
          width: 100vw;
          position: fixed;
          z-index: 100;
    }
}     // add this line
```

```
// SignUp.js

return (
<div className="sign-up"> // add this line
	<div
		onClick={onClose}
		className={`${openModal ? "overlay" : ""}`}
	></div>
	<Modal open={openModal} onClose={onClose} />
	<Home className="modal-home" />
</div>  // add this line
	);
```

**Comment by DrDrewCain** [comment]
Looks to be completed inside of #351 although @megbuch confirm if is the case. Will close this issue, although open if needed if the fix is included in that PR.

**Comment by megbuch** [comment]
@DrDrewCain Looks good! Fixed. Thank you!
