### ISSUE TITLE
Bug: Project Page button

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#354]
Need to remove blue underline on hover on button labelled "Explore Exoplanetarium"

**Comment by DrDrewCain** [comment]
Do we want to keep the underline? If anything we probably could just add a style to remove the textDecoration to none? like Style={{ textDecoration: 'none' }, this will remove the underline, unless the purpose is to have it a different color but keep the underline rather than (current blue).

**Comment by lauraehiller** [comment]
No, we want to get rid of the underline!

**Comment by DrDrewCain** [comment]
Ok yeah that's what I figured by what this entailed. I'll have a PR open, that solves this tomorrow.

**Comment by lauraehiller** [comment]
Sweet, thank you!  Did you see that I updated the project dependencies?  You'll need to npm install again before submitting your pr

**Comment by DrDrewCain** [comment]
Completed #358
