### ISSUE TITLE
Enhancement: Rename files and folders

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#356]
- All component files and folders should be PascalCase as per convention, not camelCase
- All non component files should be camelCase
- All files with jsx in them should have the extension .jsx, not .js
- Update the imports for each file whose name is changed

**Comment by DrDrewCain** [comment]
Switching to PascalCase?  Also, aren't folders usually camelCase same with non-components? I've seen components following the PascalCase. 

For reference: 
https://airbnb.io/javascript/react/

**Comment by megbuch** [comment]
For React development, I was taught to use PascalCase instead of camelCase, in addition to using .jsx instead of .js. 

https://react.dev/learn/writing-markup-with-jsx

**Comment by DrDrewCain** [comment]
Huh, curious why to use Pascal instead of camelCase when it comes to react not much of a difference other than I suppose conventions 💭. I know at my company we use react pretty heavily, but we lean heavily with camelCase use--almost never use PascalCase.

**Comment by megbuch** [comment]
Yeah, my company also uses camelCase as well. I have no idea why Pascal was taught to us, or where it comes from, honestly. 🤔

**Comment by lauraehiller** [comment]
Yes, we'll be switching to PascalCase for component files and folders! I learned PascalCase is the convention for React components, although I'm not sure it really matters.  I just want to pick a convention and stick with it so that the code is consistent.  Also, I didn't know that about file extensions Meghan, I'll update this ticket and add that!

**Comment by megbuch** [comment]
The tricky thing with changing the file extensions is that this may break imports, but they _may_ auto-update, which would make things a lot easier.

**Comment by lauraehiller** [comment]
Good point, updating the imports is a necessary piece of this as well.  I'll add that to the card too.

**Comment by DrDrewCain** [comment]
> * All component files and folders should be PascalCase as per convention, not camelCase
> * All non component files should be camelCase
> * All files with jsx in them should have the extension .jsx, not .js
> * Update the imports for each file whose name is changed



> Good point, updating the imports is a necessary piece of this as well. I'll add that to the card too.

Running into issue where npm run build is not updating bundle.js 💭  any clue why that might be the case? I do know that when running npm run build it builds a new folder called .build or in my case, moved it into dist builds a new folder called 'build' inside of dist.
