### ISSUE TITLE
Enhancement: Add Title to About Page

### ISSUE THREAD

**Issue by annakreno** [spacelabdev/spacelab-react#390]
Each sub-page of a website should have a unique and descriptive title that reflects its specific content or purpose.

For example:
- Main Title: "Spacelab" (used on home page)
- About Page Title: "Spacelab - About Us" or "About Spacelab"

Each sub-page title should be concise, relevant, and provide a clear indication of the page's purpose. Including keywords related to the content can also be beneficial for search engine optimization (SEO).

**Comment by fjstria** [comment]
Closing this issue because the About Page is currently being redesigned and updated. See #462.
