### ISSUE TITLE
Bug: 10 File Paths Incorrect, Causing Errors

### ISSUE THREAD

**Issue by annakreno** [spacelabdev/spacelab-react#397]
- ERROR in ./src/main.jsx 13:0-46 | Module not found: Error: Cannot find file: 'Podcast.jsx' does not match the corresponding name on disk: './src/pages/Podcast/podcast'.

- ERROR in ./src/pages/about/teamSlider/CohortsSlider/CohortsSlider.jsx 6:0-47 | Module not found: Error: Cannot find file: 'SliderNav.jsx' does not match the corresponding name on disk: './src/pages/about/teamSlider/SliderNav/sliderNav'.

- ERROR in ./src/pages/about/teamSlider/CurrentTeamSlider/CurrentTeamSlider.jsx 6:0-47 | Module not found: Error: Cannot find file: 'SliderNav.jsx' does not match the corresponding name on disk: './src/pages/about/teamSlider/SliderNav/sliderNav'.

- ERROR in ./src/pages/landingPages/donate/pages/DonateLandingPage.jsx 6:0-67 | Module not found: Error: Cannot find file: 'TitleSection.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/TitleSection/titleSection'. 

- ERROR in ./src/pages/landingPages/donate/pages/DonateLandingPage.jsx 7:0-100 | Module not found: Error: Cannot find file: 'AboutOrgIdentitySection.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/AboutOrgIdentitySection/aboutOrgIdentitySection'.

- ERROR in ./src/pages/landingPages/donate/pages/DonateLandingPage.jsx 8:0-97 | Module not found: Error: Cannot find file: 'CompanyProgressSection.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/CompanyProgressSection/companyProgressSection'.

- ERROR in ./src/pages/landingPages/donate/pages/DonateLandingPage.jsx 9:0-85 | Module not found: Error: Cannot find file: 'TestimonialSection.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/TestimonialSection/testimonialSection'.

- ERROR in ./src/pages/landingPages/donate/pages/DonatePaymentPage.jsx 7:0-82 | Module not found: Error: Cannot find file: 'DonatePaymentForm.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/DonatePaymentForm/donatePaymentForm'.

- ERROR in ./src/pages/landingPages/donate/pages/DonatePaymentPage.jsx 8:0-88 | Module not found: Error: Cannot find file: 'DonatePaymentHeader.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/DonatePaymentHeader/donatePaymentHeader'.

- ERROR in ./src/pages/landingPages/donate/pages/DonateSuccessPage.jsx 6:0-88 | Module not found: Error: Cannot find file: 'DonatePaymentHeader.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/DonatePaymentHeader/donatePaymentHeader'.

- ERROR in ./src/pages/landingPages/donate/pages/DonateSuccessPage.jsx 7:0-91 | Module not found: Error: Cannot find file: 'DonateSuccessMessage.jsx' does not match the corresponding name on disk: './src/pages/landingPages/donate/components/DonateSuccessMessage/donateSuccessMessage'.

**Comment by lauraehiller** [comment]
Hi Anna,

A lot of people had this error after I merged the PR with file name changes.  You should be able to resolve the errors by renaming your folders so that they match the import path :)

**Comment by annakreno** [comment]
Got it! Thank you for clarifying :)
