### ISSUE TITLE
Enforce file structure for pages and components

### ISSUE THREAD

**Issue by ryanfchase** [spacelabdev/spacelab-react#464]
### Overview
We need to make sure that the pages and components directories have the corresponding files, currently they are mixed.

### Action Items
- [ ] Research and define what is a page vs what is a component
  - [ ] write your findings in a comment
- [ ] Move all components into `components` directory
- [ ] Move all pages into `pages` directory

### Resources
- possibly useful: https://legacy.reactjs.org/docs/faq-structure.html

**Comment by fjstria** [comment]
On second thought, the file structure of the website is ok. I think it's Exoplanetarium I wanted to look at.
