### ISSUE TITLE
Add Solar System image to home page

### ISSUE THREAD

**Issue by bcantello** [spacelabdev/spacelab-react#95]
This should be component and live in the components directory as we may want to use it in other places in the future. 

Image can be found in figma:
https://www.figma.com/file/qiv8wfcRSUdNxd5oVWTBh1/SPACELAB?node-id=1192%3A51877

**Comment by lauraehiller** [comment]
In Figma, this image only shows up on mobile.  Not sure if we want it to show on Desktop too, but for now I'm leaving it.
