### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by bcantello** [spacelabdev/spacelab-react#98]
Should be completed after tickets https://github.com/spacelabdev/spacelab-react/issues/96, https://github.com/spacelabdev/spacelab-react/issues/97 and https://github.com/spacelabdev/spacelab-react/issues/99

Update footer with new page links and Social Media icons. See figma page:
https://www.figma.com/file/qiv8wfcRSUdNxd5oVWTBh1/SPACELAB?node-id=1192%3A47202

**Comment by rrriiiyyyaaa** [comment]
Assign this to me.
